version: '3'

networks:
  postgres:
    driver: bridge

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres-socks
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    networks:
      - postgres
    volumes:
      - ./docker/01-init-database.sql:/docker-entrypoint-initdb.d/01-init-database.sql
